# Generated by Django 3.0.7 on 2020-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/connect/'),
        ),
    ]
