# Generated by Django 3.0.7 on 2020-08-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200808_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/skills/'),
        ),
    ]
